name: thesis
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - scikit-learn
  - dacite
  - networkx
  - rdkit
  - tqdm
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch
    - torchvision
    - torchaudio
    - x_transformers==1.26.2