name: molgen
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python<3.12
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda
  - dacite
  - networkx
  - rdkit
  - matplotlib
  - seaborn
  - wandb
  - tqdm
  - pip:
    - build
    - cmake
    - ninja
    - wheel
    - flash-attn --no-build-isolation
    - x_transformers==1.26.2
    - selfies